### PR TITLE
resolves issues 1, 2, 3 and fixes/adjusts Snakemake rules

### PR DESCRIPTION
**Pull request by asyakhl**
new flags --assemblers and --coverage; updated flye; fixed/adjusted flye_assembly, hifiasm, stats_busco and quality_check rules.

### CODE REVIEW

**Review by skchronicles — COMMENTED** [review]
@asyakhl It looks like you may have committed a temp file. Do we need `workflow/.Snakefile.swp`? Please let me know what you think. Everything else looks good!

**Comment by asyakhl** [comment]
> @asyakhl It looks like you may have committed a temp file. Do we need `workflow/.Snakefile.swp`? Please let me know what you think. Everything else looks good!

@skchronicles No, we don't need this file.

**Comment by skchronicles** [comment]
@asyakhl Okay, that sounds good. Can you remove this file from the PR?

**Review by skchronicles — APPROVED** [review]
Thank you for removing this file!

**Pull request merged**
